<a href="https://colab.research.google.com/github/josem361/PythonBootcamp/blob/main/Module%201/Session%206/m1s6nb2_numpy_additional_functionality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Random Numbers, Aggregations/Reductions, and Universal Functions

This notebook is a quick overview of some additional functionality in Numpy. It is intended to supplement the videos and the other parts of this assignment.

In [1]:
import sys
print(sys.version)

import numpy as np
print(np.__version__)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
1.25.2


# Random numbers #

Numpy has a rich collection of (pseudo) random number generators. See the documentation for [numpy.random](https://numpy.org/doc/stable/reference/random/index.html) for more details.

In [2]:
from numpy.random import default_rng
rng = default_rng()

A = rng.integers(-10, 10, size=(4, 3)) # return random integers from -10 (inclusive) to 10 (exclusive)
print(A)

[[ 4  2  4]
 [-4  3  6]
 [ 9 -2  4]
 [-5  2  1]]


In [3]:
np.mean(A.T, axis=1)

array([1.  , 1.25, 3.75])

# Aggregations or reductions #

Suppose you want to reduce the values of a Numpy array to a smaller number of values. Numpy provides a number of such functions that _aggregate_ values. Examples of aggregations include sums, min/max calculations, and averaging, among others.

In [4]:
print("np.max =", np.max(A),"; np.amax =", np.amax(A)) # np.max() and np.amax() are synonyms
print("np.min =",np.min(A),"; np.amin =", np.amin(A)) # same
print("np.sum =",np.sum(A))
print("np.mean =",np.mean(A))
print("np.std =",np.std(A))

np.max = 9 ; np.amax = 9
np.min = -5 ; np.amin = -5
np.sum = 24
np.mean = 2.0
np.std = 3.872983346207417


The above examples aggregate over all values. But you can also aggregate along a dimension using the optional `axis` parameter.

In [5]:
print("Max in each column:", np.amax(A, axis=0)) # i.e., aggregate along axis 0, the rows, producing column maxes
print("Max in each row:", np.amax(A, axis=1)) # i.e., aggregate along axis 1, the columns, producing row maxes

Max in each column: [9 3 6]
Max in each row: [4 6 9 2]


# Universal functions

Universal functions apply a given function _elementwise_ to one or more Numpy objects.

For instance, `np.abs(A)` takes the absolute value of each element.

In [6]:
print(A, "\n==>\n", np.abs(A))

[[ 4  2  4]
 [-4  3  6]
 [ 9 -2  4]
 [-5  2  1]] 
==>
 [[4 2 4]
 [4 3 6]
 [9 2 4]
 [5 2 1]]


Some universal functions accept multiple, compatible arguments. For instance, here, we compute the _elementwise maximum_ between two matrices, $A$ and $B$, producing a new matrix $C$ such that $c_{ij} = \max(a_{ij}, b_{ij})$.

> The matrices must have compatible shapes, which we will elaborate on below when we discuss Numpy's _broadcasting rule_.

In [7]:
print(A) # recall A

[[ 4  2  4]
 [-4  3  6]
 [ 9 -2  4]
 [-5  2  1]]


In [8]:
B = rng.integers(-10, 10, size=A.shape)
print(B)

[[-2 -2 -2]
 [ 2 -3  6]
 [-4 -3  7]
 [-1 -4  6]]


In [9]:
C = np.maximum(A, B) # elementwise comparison
print(C)

[[ 4  2  4]
 [ 2  3  6]
 [ 9 -2  7]
 [-1  2  6]]


You can also build your own universal functions! For instance, suppose we want a way to compute, elementwise, $f(x) = e^{-x^2}$ and we have a scalar function that can do so:

In [10]:
def f(x):
    from math import exp
    return exp(-(x**2))

This function accepts one input (`x`) and returns a single output. The following will create a new Numpy universal function `f_np`.
See the documentation for [np.frompyfunc()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.frompyfunc.html) for more details.

In [11]:
f_np = np.frompyfunc(f, 1, 1)

print(A, "\n=>\n", f_np(A))

[[ 4  2  4]
 [-4  3  6]
 [ 9 -2  4]
 [-5  2  1]] 
=>
 [[1.1253517471925912e-07 0.01831563888873418 1.1253517471925912e-07]
 [1.1253517471925912e-07 0.00012340980408667956 2.3195228302435696e-16]
 [6.639677199580735e-36 0.01831563888873418 1.1253517471925912e-07]
 [1.3887943864964021e-11 0.01831563888873418 0.36787944117144233]]


## What are your questions on these topics?